### ISSUE TITLE
Pipenv 2018 fails to install thoth-ssdeep

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/python-ssdeep#1]
##### ISSUE TYPE

- Bug Report

##### Python ssdeep VERSION
Issue log - https://github.com/thoth-station/python-ssdeep
As suggested in chat building it for older manylinux standard might fix the issue.

**Comment by fridex** [comment]
manylinux 2010 compliant wheel files for Python 3.6 and Python 3.8 built and available on PyPI:

https://pypi.org/project/thoth-ssdeep/3.4/#files
